apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment-service
  description: Handles payment processing for DevPortal platform
  annotations:
    github.com/project-slug: devportal-labs/payment-service
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: payment-service
    argocd/app-name: payment-service
  tags:
    - python
    - microservice
spec:
  type: service
  lifecycle: production
  owner: platform-engineers
  system: devportal-platform
